### ISSUE TITLE
percentPrecision Not Work

### ISSUE THREAD

**Issue by consciousnessdev** [Neckster/chartjs-plugin-piechart-outlabels#12]
This is my data and option

`datasets: [
        {
          data: [9670, 21],
        }
      ]
`
`
options: {
  outlabels: {
          display: true,
          text: "%l %p",
          percentPrecision: 2,
  }
}
`

it shows
data 1 = 100%
data 2 = 0%

my desired value is 
data 1 = 99.78%
data 2 = 0.22%

**Comment by huangdaphne3** [comment]
not working for me as well

**Comment by czarnobiaua** [comment]
I’ll second that. I would like to ask for a fix. Thanks!

**Comment by plnagaraju** [comment]
For me also it is not working.

**Comment by felipyamorim** [comment]
Try to use %p.2

**Comment by Tiagochicoo** [comment]
@felipyamorim's sugestion works perfectly. Thank you!

**Comment by consciousnessdev** [comment]
> Try to use %p.2

wow 2020, thanks for suggestion @felipyamorim !

**Comment by mcheung610** [comment]
whoa thanks for the tips. Someone should probably update the readme.
